### ISSUE TITLE
I Cannot Program Email Image Token in a Flow

### ISSUE THREAD

**Issue by Jansrt** [jordenc/email-sender#15]
I cannot program to email an image token into a flow. I can select the cards 'Make an Image as Token' and 'Email image token', but I cannot make the link to the token. When I click on the tag in the Email Card no options show up and the search does not work. 

I can send emails and the test email went wel too.

Does this problem need to be fixed or am I missing something?

**Comment by jordenc** [comment]
You need to flows to do that.

**First flow:** 
Use whatever card you need in the "When" field. In the "Then" field, use the "Make an image as token".

**Second flow:**
In the "When" field in Homey, use the "A snapshot was taken" card from ImageGrabber or Synology (I think you want to do this? Otherwise use the trigger card from the other source you want to use).

In the "Then" field in Homey, use the "Send an image by email"-card from this app. Use the _local_ image tag from ImageGrabber/Synology.
