### ISSUE TITLE
in firmware version 0.10.0 all email settings from the app (like username, password and SMTP) are lost after every reboot.

### ISSUE THREAD

**Issue by sleutelsnet** [jordenc/email-sender#3]

**Comment by jordenc** [comment]
Is that a reboot from the system or a reboot by pulling the plug on Homey?

I just tested with a 'software' reboot (using the system) and experienced no problems. It might be a problem with the Homey software since it uses the correct functions to save and load the settings.

You might want to run this app in developer mode (see https://developers.athom.com for more information) to see if something weird happens when it starts (it should say: "Backend settings updated" at the start) and when you save variables (it should say something like:
"variable mail_user has been set.
Backend settings updated
variable mail_password has been set.
Backend settings updated")

**Comment by jordenc** [comment]
No reactions after a few months so I'll close it. Feel free to reopen if the problem persists with the latest version.
